version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: agendafacil_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: agendafacil
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - agendafacil_network

  backend:
    build: 
      context: ./backend
      # O network host no build ajuda a evitar erros de DNS no npm install
      network: host 
    container_name: agendafacil_api
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/agendafacil
    networks:
      - agendafacil_network

  frontend:
    build: 
      context: ./frontend
      network: host
    container_name: agendafacil_ui
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always
    ports:
      - "8070:80"
    networks:
      - agendafacil_network
      - rede-proxy-reverso
    depends_on:
      - backend

networks:
  agendafacil_network:
    driver: bridge
  # Certifique-se que esta rede j√° existe no Portainer/Docker:
  # docker network create rede-proxy-reverso
  rede-proxy-reverso:
    external: true

volumes:
  pg_data:
